### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "memil88@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json